site_name: NETMVAS Documentation

site_url: https://NETMVAS.github.io/NETMVAS.github.io

nav:
    - Главная: index.md
    - Multivendor Ansible:
        - Главная: multivendor_ansible/index.md
        - Roles: multivendor_ansible/roles/index.md
    - Feecc:
        - Главная: feecc/index.md
        - Spoke: feecc/spoke.md
        - Hub: feecc/hub.md
    - Multi Edge Computing:
        - Main: multi_edge_computing/index.md

theme:
  name: material
  language: ru
  palette:
    primary: white
  logo: icon.png
  favicon: icon.png

markdown_extensions:
  - attr_list
