site_name: NETMVAS Documentation

site_url: https://NETMVAS.github.io/NETMVAS.github.io

nav:
    - Главная: index.md
    - Установка: setup.md
    - Роли: roles/index.md

theme:
  name: material
  language: ru
  palette:
    primary: white
  logo: icon.png
  favicon: icon.png
